export enum ConfigVar {
  HOST = 'HOST',
  PORT = 'PORT',

  // Database
  MONGODB_URI = 'MONGODB_URI',

  // Authentication
  JWT_SECRET = 'JWT_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',

  FACEBOOK_APP_ID = 'FACEBOOK_APP_ID',
  FACEBOOK_APP_SECRET = 'FACEBOOK_APP_SECRET',
  FACEBOOK_CALLBACK_URL = 'FACEBOOK_CALLBACK_URL',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',

  // Default admin account
  DEFAULT_ADMIN_EMAIL = 'DEFAULT_ADMIN_EMAIL',
  DEFAULT_ADMIN_PASSWORD = 'DEFAULT_ADMIN_PASSWORD',
}
